version: '3'
services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
volumes:
  db-store: